eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      uri:  mongodb://localhost:27017/food-orders-db
      host: localhost
      port: 27017
      database: food-orders-db
      repositories:
        enabled: true
  application:
    name: FOOD-ORDERING-SERVICE        
server:
  port: 8093