eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  data:
    mongodb:
      uri:  mongodb://localhost:27017/food-order-db
      host: localhost
      port: 27017
      database: food-order-db
      repositories:
        enabled: true
  application:
    name: FOOD-ORDERING-SERVICE        
server:
  port: 8093
  
logging:
  file:
    name: order-management.log
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"